import { InterpretationStep } from '../types';

const steps: InterpretationStep[] = [
  { step: 1, title: 'Frecuencia cardíaca', finding: 'Calcular FC en lpm', normal: '60-100 lpm', pathological: '< 60 (bradicardia) o > 100 (taquicardia)' },
  { step: 2, title: 'Ritmo', finding: 'Evaluar regularidad del RR', normal: 'Regular', pathological: 'Irregular, regularmente irregular, irregularmente irregular' },
  { step: 3, title: 'Onda P', finding: 'Analizar morfología, eje, y relación con QRS', normal: 'Presente, positiva en DII, precede cada QRS', pathological: 'Ausente, múltiple, retrógrada, picuda, o disociada del QRS' },
  { step: 4, title: 'Intervalo PR', finding: 'Medir desde inicio P hasta inicio QRS', normal: '0.12-0.20 s (3-5 cuadros chicos)', pathological: '< 0.12 (preexcitación), > 0.20 (bloqueo AV 1°), o variable' },
  { step: 5, title: 'QRS', finding: 'Medir duración, evaluar morfología en precordiales', normal: '< 0.12 s (3 cuadros chicos), progresión R normal', pathological: '≥ 0.12 s (bloqueo rama, TV), mala progresión R, ondas Q patológicas' },
  { step: 6, title: 'Eje eléctrico', finding: 'Calcular eje QRS en frontal', normal: '0° a +90°', pathological: 'Desviado a izquierda (-30° a -90°), derecha (> +90°), o extremo (-90° a -180°)' },
  { step: 7, title: 'Segmento ST y onda T', finding: 'Analizar elevación/depresión ST y morfología T', normal: 'ST isoeléctrico, T concordante con QRS', pathological: 'Supradesnivel (IAM), infradesnivel (isquemia), T invertida, T picuda simétrica (hiperK)' },
  { step: 8, title: 'Conclusión diagnóstica', finding: 'Integrar todos los hallazgos', normal: 'Ritmo Sinusal Normal', pathological: 'Identificar arritmia específica y correlación clínica' },
];

export const BASE_STEPS = steps;

export const getArrhythmiaInterpretation = (id: string): InterpretationStep[] => {
  const map: Record<string, Partial<InterpretationStep>[]> = {
    nsr: [
      { step: 1, pathological: '60-100 lpm — normal' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Normal, positiva en DII, una por cada QRS' },
      { step: 4, pathological: '0.12-0.20 s, constante' },
      { step: 5, pathological: '< 0.12 s, progresión normal R en precordiales' },
      { step: 6, pathological: '0° a +90° (normal)' },
      { step: 7, pathological: 'ST isoeléctrico, T concordante' },
      { step: 8, pathological: 'Ritmo Sinusal Normal. No requiere intervención.' },
    ],
    sinus_brady: [
      { step: 1, pathological: '< 60 lpm' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Normal, precede cada QRS' },
      { step: 4, pathological: '0.12-0.20 s, normal' },
      { step: 5, pathological: 'Normal (< 0.12 s)' },
      { step: 6, pathological: 'Normal (0° a +90°)' },
      { step: 7, pathological: 'Normal' },
      { step: 8, pathological: 'Bradicardia Sinusal. Evaluar causa (atletas, vagotonía, fármacos, hipotiroidismo). Tratar solo si sintomático.' },
    ],
    sinus_tachy: [
      { step: 1, pathological: '> 100 lpm' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Normal, puede ser picuda si FC muy alta' },
      { step: 4, pathological: '0.12-0.20 s (puede acortarse con FC alta)' },
      { step: 5, pathological: 'Normal (< 0.12 s)' },
      { step: 6, pathological: 'Normal' },
      { step: 7, pathological: 'Puede haber infradesnivel ST upsloping por taquicardia' },
      { step: 8, pathological: 'Taquicardia Sinusal. Buscar causa: fiebre, dolor, ansiedad, hipovolemia, anemia. Tratar causa base.' },
    ],
    pac: [
      { step: 1, pathological: '70 lpm base, con latido prematuro' },
      { step: 2, pathological: 'Irregular por latido prematuro' },
      { step: 3, pathological: 'Onda P prematura con morfología diferente a la sinusal' },
      { step: 4, pathological: 'PR puede ser diferente al sinusal' },
      { step: 5, pathological: 'Estrecho (< 0.12 s)' },
      { step: 6, pathological: 'Normal' },
      { step: 7, pathological: 'Normal' },
      { step: 8, pathological: 'Extrasístole Auricular (CAP). Benigna si aislada. Evaluar frecuencia y síntomas.' },
    ],
    afib_moderate: [
      { step: 1, pathological: 'Variable, 60-100 lpm' },
      { step: 2, pathological: 'Irregularmente irregular' },
      { step: 3, pathological: 'Ausente. Actividad auricular caótica (ondas f)' },
      { step: 4, pathological: 'No medible' },
      { step: 5, pathological: 'Estrecho (< 0.12 s)' },
      { step: 6, pathological: 'Variable' },
      { step: 7, pathological: 'Variable' },
      { step: 8, pathological: 'Fibrilación Auricular Moderada. Evaluar anticoagulación, control de frecuencia, y riesgo de ACV.' },
    ],
    afib_low: [
      { step: 1, pathological: '40-60 lpm' },
      { step: 2, pathological: 'Irregularmente irregular' },
      { step: 3, pathological: 'Ausente. Ondas f finas' },
      { step: 4, pathological: 'No medible' },
      { step: 5, pathological: 'Estrecho (< 0.12 s)' },
      { step: 6, pathological: 'Variable' },
      { step: 7, pathological: 'Variable' },
      { step: 8, pathological: 'FA con respuesta ventricular lenta. Puede ser por fármacos o enfermedad del nodo AV.' },
    ],
    afib_high: [
      { step: 1, pathological: '120-160 lpm (respuesta rápida)' },
      { step: 2, pathological: 'Irregularmente irregular' },
      { step: 3, pathological: 'Ausente. Ondas f prominentes' },
      { step: 4, pathological: 'No medible' },
      { step: 5, pathological: 'Estrecho (< 0.12 s)' },
      { step: 6, pathological: 'Variable' },
      { step: 7, pathological: 'Variable' },
      { step: 8, pathological: 'FA con respuesta ventricular rápida. Riesgo de inestabilidad hemodinámica.' },
    ],
    aflutter: [
      { step: 1, pathological: 'Auricular ~300 lpm, Ventricular ~150 lpm (2:1)' },
      { step: 2, pathological: 'Regular si bloqueo fijo; variable si bloqueo variable' },
      { step: 3, pathological: 'Ondas F en "diente de sierra", negativas en DII, DIII, aVF' },
      { step: 4, pathological: 'No medible' },
      { step: 5, pathological: 'Estrecho (< 0.12 s)' },
      { step: 6, pathological: 'Variable' },
      { step: 7, pathological: 'Puede haber cambios por FC rápida' },
      { step: 8, pathological: 'Aleteo Auricular. Evaluar anticoagulación. Considerar cardioversión o ablación.' },
    ],
    psvt: [
      { step: 1, pathological: '150-250 lpm (muy rápida)' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Onda P a menudo no visible (oculta en QRS o T)' },
      { step: 4, pathological: 'No medible' },
      { step: 5, pathological: 'Estrecho (< 0.12 s)' },
      { step: 6, pathological: 'Normal o ligeramente desviado' },
      { step: 7, pathological: 'Puede haber infradesnivel ST por taquicardia' },
      { step: 8, pathological: 'TPSV. Maniobras vagales. Adenosina si estable. Cardioversión si inestable.' },
    ],
    avnrt: [
      { step: 1, pathological: '170 lpm' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Onda P retrógrada: puede crear pseudo-S en II o pseudo-R\' en V1' },
      { step: 4, pathological: 'No aplicable (P ocurre durante o después del QRS)' },
      { step: 5, pathological: 'Estrecho (< 0.12 s)' },
      { step: 6, pathological: 'Normal' },
      { step: 7, pathological: 'Normal o cambios inespecíficos' },
      { step: 8, pathological: 'TRNAV. Taquicardia por reentrada nodal AV. Manejo igual a TPSV.' },
    ],
    junctional_escape: [
      { step: 1, pathological: '40-60 lpm' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Ausente o retrógrada (invertida en DII)' },
      { step: 4, pathological: 'No aplicable (PR corto o P después del QRS)' },
      { step: 5, pathological: 'Estrecho (< 0.12 s)' },
      { step: 6, pathological: 'Normal' },
      { step: 7, pathological: 'Normal' },
      { step: 8, pathological: 'Ritmo de Escape de la Unión. Mecanismo de seguridad. Buscar causa del fallo del nodo sinusal.' },
    ],
    avb_1st_degree: [
      { step: 1, pathological: '70 lpm (puede ser normal o bradicárdico)' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Normal, precede cada QRS' },
      { step: 4, pathological: '> 0.20 s (prolongado y constante)' },
      { step: 5, pathological: 'Normal (< 0.12 s)' },
      { step: 6, pathological: 'Normal' },
      { step: 7, pathological: 'Normal' },
      { step: 8, pathological: 'BAV 1er Grado. Generalmente benigno. Monitorear si hay progresión.' },
    ],
    avb_2nd_degree_mobitz_I: [
      { step: 1, pathological: 'Bradicárdico (~45 lpm efectivos)' },
      { step: 2, pathological: 'Regularmente irregular (agrupamiento de latidos)' },
      { step: 3, pathological: 'Normal, una onda P bloqueada cada ciclo' },
      { step: 4, pathological: 'Se alarga progresivamente hasta bloqueo de la P' },
      { step: 5, pathological: 'Normal (< 0.12 s)' },
      { step: 6, pathological: 'Normal' },
      { step: 7, pathological: 'Normal' },
      { step: 8, pathological: 'BAV 2° Mobitz I (Wenckebach). Benigno, típicamente nodal. Observar.' },
    ],
    avb_2nd_degree_mobitz_II: [
      { step: 1, pathological: 'Bradicárdico (~40 lpm efectivos)' },
      { step: 2, pathological: 'Regularmente irregular' },
      { step: 3, pathological: 'Normales, algunas no conducen' },
      { step: 4, pathological: 'Constante en latidos conducidos' },
      { step: 5, pathological: 'Puede ser ancho (≥ 0.12 s) por bloqueo infranodal' },
      { step: 6, pathological: 'Variable' },
      { step: 7, pathological: 'Normal' },
      { step: 8, pathological: 'BAV 2° Mobitz II. PELIGROSO: riesgo de progresión a bloqueo completo. Considerar marcapasos.' },
    ],
    avb_3rd_degree: [
      { step: 1, pathological: 'Auricular ~60-80 lpm, Ventricular 20-40 lpm' },
      { step: 2, pathological: 'Regular P-P y R-R independientes (disociación AV completa)' },
      { step: 3, pathological: 'Normales, sin relación con QRS' },
      { step: 4, pathological: 'Variable (no hay conducción AV)' },
      { step: 5, pathological: 'Ancho (≥ 0.12 s, escape ventricular)' },
      { step: 6, pathological: 'Variable' },
      { step: 7, pathological: 'Normal' },
      { step: 8, pathological: 'BAV Completo (3er Grado). EMERGENCIA. Marcapasos transcutáneo y luego definitivo.' },
    ],
    wpw: [
      { step: 1, pathological: '70 lpm (puede tener episodios de taquicardia)' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Normal' },
      { step: 4, pathological: '< 0.12 s (acortado por preexcitación)' },
      { step: 5, pathological: '≥ 0.12 s con onda delta (empinamiento inicial del QRS)' },
      { step: 6, pathological: 'Puede estar desviado según la vía accesoria' },
      { step: 7, pathological: 'Puede haber cambios secundarios por conducción anormal' },
      { step: 8, pathological: 'WPW (Wolf-Parkinson-White). Preexcitación ventricular. Riesgo de taquicardias. Evaluar ablación.' },
    ],
    pvc: [
      { step: 1, pathological: 'Depende del ritmo base' },
      { step: 2, pathological: 'Irregular por latido prematuro ventricular' },
      { step: 3, pathological: 'Normal en latidos sinusales; ausente en CVP' },
      { step: 4, pathological: 'Normal en latidos sinusales' },
      { step: 5, pathological: 'Ancho > 0.12 s, bizarro. Pausa compensatoria completa' },
      { step: 6, pathological: 'Eje del CVP opuesto al normal' },
      { step: 7, pathological: 'T discordante (opuesta al QRS del CVP)' },
      { step: 8, pathological: 'CVP (Contracción Ventricular Prematura). Benigna si aislada. Evaluar frecuencia y cardiopatía.' },
    ],
    vtach: [
      { step: 1, pathological: '180 lpm (100-270)' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Ondas P disociadas visibles (AV dissociation) — signo específico de TV' },
      { step: 4, pathological: 'No medible (disociación AV)' },
      { step: 5, pathological: 'Ancho ≥ 0.12 s, concordancia precordial negativa (QS en V1-V6)' },
      { step: 6, pathological: 'Extremo (-90° a -180°)' },
      { step: 7, pathological: 'T discordante con QRS' },
      { step: 8, pathological: 'Taquicardia Ventricular. EMERGENCIA. Evaluar pulso. Si sin pulso: desfibrilar + RCP. Si con pulso: amiodarona, cardioversión.' },
    ],
    torsades: [
      { step: 1, pathological: '200 lpm (150-250)' },
      { step: 2, pathological: 'Irregular' },
      { step: 3, pathological: 'No visible' },
      { step: 4, pathological: 'No medible' },
      { step: 5, pathological: 'Ancho, polimórfico. Los ejes rotan (±60°) alrededor de la línea de base' },
      { step: 6, pathological: 'Variable (cambia constantemente)' },
      { step: 7, pathological: 'Intervalo QT prolongado (condición de base necesaria)' },
      { step: 8, pathological: 'Torsades de Pointes. Asociado a QT largo. Tratar con sulfato de magnesio IV.' },
    ],
    vfib: [
      { step: 2, pathological: 'Caótico, sin ritmo organizado' },
      { step: 3, pathological: 'Ausentes' },
      { step: 5, pathological: 'Ausentes (actividad desorganizada, sin QRS definidos)' },
      { step: 7, pathological: 'Actividad caótica de amplitud variable' },
      { step: 8, pathological: 'Fibrilación Ventricular. PARO CARDÍACO. DESFIBRILACIÓN INMEDIATA + RCP.' },
    ],
    asystole: [
      { step: 2, pathological: 'Ausente (línea isoeléctrica plana)' },
      { step: 5, pathological: 'Ausente' },
      { step: 8, pathological: 'Asistolia. Confirmar en ≥ 2 derivaciones. RCP + Adrenalina. NO desfibrilar.' },
    ],
    ivr: [
      { step: 1, pathological: '20-40 lpm (muy lento)' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Ausente' },
      { step: 4, pathological: 'No medible' },
      { step: 5, pathological: 'Ancho (≥ 0.12 s), morfología ventricular' },
      { step: 6, pathological: 'Extremo (similar a TV)' },
      { step: 7, pathological: 'Discordante' },
      { step: 8, pathological: 'Ritmo Idioventricular. Ritmo de escape ventricular. Marcapasos si sintomático.' },
    ],
    riva: [
      { step: 1, pathological: '40-120 lpm (acelerado vs IVR)' },
      { step: 2, pathological: 'Regular' },
      { step: 3, pathological: 'Ausente' },
      { step: 4, pathological: 'No medible' },
      { step: 5, pathological: 'Ancho (≥ 0.12 s)' },
      { step: 6, pathological: 'Extremo' },
      { step: 7, pathological: 'Discordante' },
      { step: 8, pathological: 'RIVA. Común post-infarto o reperfusión. Generalmente autolimitado.' },
    ],
    rbbb: [
      { step: 1, pathological: 'Depende del ritmo base' },
      { step: 5, pathological: '≥ 0.12 s. rSR\' en V1-V2. S ancha en DI, V5-V6' },
      { step: 6, pathological: 'Puede estar normal o desviado a derecha' },
      { step: 7, pathological: 'T discordante en V1-V2 (negativa)' },
      { step: 8, pathological: 'Bloqueo de Rama Derecha. Puede ser benigno o asociado a cardiopatía.' },
    ],
    lbbb: [
      { step: 1, pathological: 'Depende del ritmo base' },
      { step: 5, pathological: '≥ 0.12 s. QS en V1-V2. R mellada ("M") en V5-V6' },
      { step: 6, pathological: 'Desviado a izquierda (común)' },
      { step: 7, pathological: 'T discordante (negativa en V5-V6)' },
      { step: 8, pathological: 'Bloqueo de Rama Izquierda. Generalmente asociado a cardiopatía estructural.' },
    ],
    wandering_pacemaker: [
      { step: 2, pathological: 'Irregular' },
      { step: 3, pathological: '≥ 3 morfologías de P distintas' },
      { step: 4, pathological: 'Variable' },
      { step: 5, pathological: 'Normal' },
      { step: 8, pathological: 'Marcapaso Migratorio (Errante). Ritmo benigno, frecuencia < 100 lpm. No requiere tratamiento.' },
    ],
    mat: [
      { step: 1, pathological: '> 100 lpm (130-170)' },
      { step: 2, pathological: 'Irregularmente irregular' },
      { step: 3, pathological: '≥ 3 morfologías de P distintas' },
      { step: 4, pathological: 'Variable' },
      { step: 5, pathological: 'Normal (< 0.12 s)' },
      { step: 8, pathological: 'Taquicardia Auricular Multifocal. Asociada a EPOC severa. Tratar causa base.' },
    ],
    bigeminy: [
      { step: 2, pathological: 'Bigeminia: patrón normal + CVP repetitivo' },
      { step: 3, pathological: 'Normal en latidos sinusales' },
      { step: 5, pathological: 'Normal alternando con CVP ancho' },
      { step: 8, pathological: 'Bigeminismo Ventricular. Evaluar causa y frecuencia. Considerar Holter.' },
    ],
    trigeminy: [
      { step: 2, pathological: 'Trigeminia: dos normales + un CVP alternando' },
      { step: 3, pathological: 'Normal en latidos sinusales' },
      { step: 5, pathological: 'Normal alternando con CVP ancho' },
      { step: 8, pathological: 'Trigeminismo Ventricular. Evaluar causa y frecuencia.' },
    ],
  };

  const customSteps = map[id];
  if (!customSteps) return BASE_STEPS;

  return BASE_STEPS.map(base => {
    const custom = customSteps.find(s => s.step === base.step);
    return custom ? { ...base, ...custom } : base;
  });
};
